### ISSUE TITLE
Pagination serial number issue

### ISSUE THREAD

**Issue by php-dev2** [jmvtrinidad/angular2-datagrid#2]
Hi there,

    I am having difficulties in generating serial numbers page wise. I don't want to show primary key as ID. Please guide me a little @jmvtrinidad . 

Thanks in advance.

**Comment by jmvtrinidad** [comment]
Can you add your code for further information. It will be also helpful if you add a running jsfiddle or plunker demo.

**Comment by jmvtrinidad** [comment]
Please elaborate your issue, I will close this until you came back for more information about your problems. Thanks!
