### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by mail19** [jmvtrinidad/angular2-datagrid#7]
Hello,
I'm getting this error. I did look around and some says this is caused by webpack. Any insights/suggestions?

Thanks!

...\node_modules\angular2-datagrid\src\app\datagrid\ng-datagrid.model.ts Unexpected token (3:28)
You may need an appropriate loader to handle this file type.
| import './../utils/object.extensions';
| 
| export class NgDataGridModel<T> {
| searchValue: T = <T>{};
| currentPageIndex: number = 1;
at new Error (native)
.
.
.

**Comment by jmvtrinidad** [comment]
Hi, can you post your class? 
How do you import it in your class?

**Comment by mail19** [comment]
Hi,
On my component: 
```
import { NgDataGridModel } from 'angular2-datagrid';

export class MyComponent {
 public table: NgDataGridModel<FileTest>;

 constructor()
 {
  this.table = new NgDataGridModel<FileTest>([]);        
 }
}
```

I use this FileTest class for the data grid (instead of user User on your example)
FileTest class: 
```
export class FileTest {
    public name: string;
    public size: number;
    public active: boolean;
}
```



Please let me know and thanks for the quick reply.

**Comment by mail19** [comment]
No need to add anything on the app.module.ts. Is that right?

**Comment by jmvtrinidad** [comment]
Hi @mail19 that should work.
`NgDataGridModel` is a class only, so importing it should work as long as it is include in your build.
And also note to omit extension for js/ts.
